// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	VideoID  int32     `gorm:"column:video_id;not null" json:"video_id"`
	UserID   int32     `gorm:"column:user_id;not null" json:"user_id"`
	Content  string    `gorm:"column:content" json:"content"`
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP" json:"create_at"`
	Author   User      `gorm:"foreignKey:UserID" json:"author"`
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
