// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID       int32     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UserID   int32     `gorm:"column:user_id;not null" json:"user_id"` // 发送方
	ToUserID int32     `gorm:"column:to_user_id" json:"to_user_id"`    // 接收方
	Content  string    `gorm:"column:content" json:"content"`
	CreateAt time.Time `gorm:"column:create_at;default:CURRENT_TIMESTAMP" json:"create_at"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
