// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePerson = "people"

// Person mapped from table <people>
type Person struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name;not null" json:"name"`
	Age  int32  `gorm:"column:age;not null" json:"age"`
}

// TableName Person's table name
func (*Person) TableName() string {
	return TableNamePerson
}
